## This file is for local development testing of the LaravelStarterKit in a project directory
## It should be added to a `.lando.local.dev.yml
services:
  appserver:
    overrides:
      ## Example mapping of a directory called "LaravelStarterKit"
      ## This directory can be referenced via composer.json as a repository source
      ## See CONTRIBUTING.md for details
      volumes:
        - ../LaravelStarterKit:/laravel-starter-kit
